### ISSUE TITLE
Reordering sidebar menu entries?

### ISSUE THREAD

**Issue by heqro** [lukeorth/poison#1]
Hi, I am currently setting up a blog according to this theme, but I cannot figure out how to reorder the sidebar entries as they seem to be ordered alphabetically. For instance, a dummy project with the following entries would build a sidebar with entries "aa, bb, cc, dd" as far as I can tell, right?

```
menu = [
        {Name = "aa", URL = "/aa/"},
        {Name = "cc", URL = "/cc/"},
        {Name = "bb", URL = "/bb/"},
        {Name = "dd", URL = "/dd/"},
    ]
```

**Comment by lukeorth** [comment]
Hi @heqro, thanks for your interest in the theme!  

Yes, currently the theme orders sidebar entries alphabetically and not in the order specified in the config.  I agree that this behavior is not preferred though.  Users should have control over how their content is ordered.

I'll try getting a fix in for this sometime next week.

**Comment by lukeorth** [comment]
@heqro I just merged a fix for this into the `master` branch.  Please let me know if it's working for you now.
