### ISSUE TITLE
Sidebar does not scroll

### ISSUE THREAD

**Issue by maccident** [lukeorth/poison#10]
On a fresh install of hugo and poison,
hugo (via brew): hugo v0.109.0+extended darwin/arm64 BuildDate=unknown
poison (via github): updated within the last 15 minutes.

The sidebar does not scroll at all, regardless of the state of the main / content section.

Unless the viewer zooms out / reduces the font size, they will not see the full content in the sidebar, such as the copyright and hugo / poison attribution.

**Comment by lukeorth** [comment]
Hi @maccident -- good catch!  I'll try to get a fix in for this soon.

**Comment by maccident** [comment]
That fixed it for Firefox, but not for safari on macOS. 
macOS requires an additional line…
here's the patch from diff:

--- themes/poison/static/css/hyde.css	2023-01-17 08:22:59
+++ static/css/hyde.css	2023-01-17 10:55:58
@@ -72,6 +72,7 @@
     width: 18rem;
     text-align: left;
     overflow-y: auto;
+    -webkit-overflow-scrolling: touch;
   }
 }
