### ISSUE TITLE
Expanded summary

### ISSUE THREAD

**Issue by JonAugust** [lukeorth/poison#105]
I'm new to Hugo and I've tried to find a setting for this, but nothing has worked.  On my index page, there are summaries of the posts, but they're collapsed.  Spacing between paragraphs conveys some meaning, so it would be good if the collapsed summary retained that formatting.  Is there a setting for keeping the formatting in the summary?  Or showing the entire post on the summary?

I tried `maxShownLines = -1` in my hugo.toml, as this seems to work with some themes, but as far as I could tell, not with Poison.  Thank you for your help!

**Comment by JonAugust** [comment]
After some additional research, I've found that Hugo is producing the Summary variable used by Poison.  If you'd like to retain the formatting for your summary, you have to manually insert the split using this: `<!--more-->` Note: it must be exactly like this - no spaces, all lowercase.  It will retain formatting up until your split.

**Comment by lukeorth** [comment]
Hi @JonAugust, sorry for my delayed response on this.

That is correct -- you'll want to use `<!--more-->` to manually split content summaries and preserve formatting.  I'll leave [this link](https://gohugo.io/content-management/summaries/) to Hugo's docs on _Content Summaries_ in case anyone else has similar problems in the future.
