### ISSUE TITLE
HTML code in .md file is ignored

### ISSUE THREAD

**Issue by JonAugust** [lukeorth/poison#108]
I'm trying to include links with a target to _blank.  I don't think markdown allows for that and I've read the solution is to just use real html:

`<a href="https://ASiteWithArticles.com/" target="_blank">Articles!</a>`

But, my Hugo/Poison environment seems to strip these completely.  Is there a solution to this issue?

Thank you for your help!

**Comment by lukeorth** [comment]
Hi, @JonAugust -- thank you for the issue.  I've personally wanted this capability for a while.  


After some research, I was able to override how Hugo renders links within the theme.  Now, all links in markdown will automatically have `target="_blank"`, so you don't need to add raw the HTML yourself.  You can also add titles to your links to give readers a better context of where the link is going to (see examples below).

### With a title
_**Markdown**_:
`This is a [test link](https://google.com/ "Google") with a title.`

_**Result**_:
![image](https://github.com/lukeorth/poison/assets/35306887/8e431bf9-a75a-471b-81b1-2f1ebf816e1e)

### Without a title
`This is a [test link](https://google.com/) without a title.`

_**Result**_:
![image](https://github.com/lukeorth/poison/assets/35306887/77d53cf2-c210-44f8-87d8-6afccabe2047)

I hope this helps! :slightly_smiling_face:

**Comment by JonAugust** [comment]
Awesome!  Thank you for adding this!
