### ISSUE TITLE
Can't build example config -- theme expects 404 page but can't find it?

### ISSUE THREAD

**Issue by AiredaleDev** [lukeorth/poison#117]
I downloaded this theme and installed the provided config, but when I tried to run `hugo` it instead did the following:

```
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
Error: Error building site: render of "404" failed: execute of template failed: template: 404.html:1:3: executing "404.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/cameron/Website/the-path/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
```

I've never used HUGO before, so presumably the 404 page wants a brand image? I tried setting that parameter, no dice.

**Comment by lukeorth** [comment]
Hi, @AiredaleDev -- thank you for reporting this.

If you run `hugo version`, what version does it say you're using?  I'm wondering if you're experiencing the same issues that CodeF0x reported [here](https://github.com/lukeorth/poison/issues/115).

**Comment by AiredaleDev** [comment]
CodeF0x appears to be running the same version as me, I'll try building Hugo from source and let you know if it works.

**Comment by AiredaleDev** [comment]
That was it! Updating to Hugo 0.116.0 fixed the problem.

**Comment by lukeorth** [comment]
Wonderful!  I'm glad to hear it.  Thank you for using the theme. :slightly_smiling_face:
