### ISSUE TITLE
Post: list of series does not show correctly 

### ISSUE THREAD

**Issue by golinuxcloudnative** [lukeorth/poison#12]
- the link in the post pointing to the current series page is wrong
  - current: http://localhost:1313//series/ 
  - expected: http://localhost:1313/series/categoryname

-  other posts in this series is showing wrongly in the post.

**Comment by lukeorth** [comment]
Hi @golinuxcloudnative, the extra forward slash in the URL is an issue (that should be fixed), but the series should work regardless.  I just added a series to the *Introducing Poison* post on the [demo site](https://poison-theme.netlify.app/) and it seems to be working fine.  [This](https://github.com/lukeorth/hydes-poison-demo-site) is the repo that builds that demo site if you want to take a look.

If you added a series to your content and are getting a 404 error at first, you may need to run `hugo server` again to refresh things.  Let me know if that fixes the issue for you.

**Comment by golinuxcloudnative** [comment]
You're right. My mistake.  I was using an array like tags in series.

Wrong
`series: ["go"]`

Correct
`series: "go"`

Awesome theme BTW.
