### ISSUE TITLE
`About` Not Showing up in sidebar

### ISSUE THREAD

**Issue by camachom** [lukeorth/poison#121]
Hello! Thanks for making this awesome theme. Here is the issue I'm running into:

I have a fairly standard config with:

```
menu = [
  { Name = "About", URL = "/about/", HasChildren = false },
  { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
] # MENU PLACEHOLDER
```

And my file structure is simple:
<img width="465" alt="Screenshot 2023-08-20 at 10 02 32 PM" src="https://github.com/lukeorth/poison/assets/15637784/4bfb5edb-07c1-4483-8117-39764dfb5b9e">

But the `About` link does not show up: [My Blog](https://camachom.github.io)
However, if I go the about page directly, it renders: https://camachom.github.io/about
Here is the [repository](https://github.com/camachom/camachom.github.io) if anybody wants to look at the code, but again, I'm not doing anything custom. 

Any ideas on how to debug? Thanks

**Comment by camachom** [comment]
@lukeorth thanks for looking into it. 

I did some further investigation, and it seems to be happening even on a completely new project. I started a new Hugo site from scratch and added the sample config: https://github.com/camachom/poison-test/tree/master

This leads me to believe something is wrong with my local or with a dependency. This is what I'm using:
- macOS Ventura 13.5.1
- hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended darwin/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=brew
- tested on both Safari and Chrome both locally and after deploying to Github pages

**Comment by camachom** [comment]
I figured it out! I think the issue comes from having two config files. I had a `config.toml` from cloning `poison` in `themes/poison` and then a `hugo.toml` from making a new site in my root. Once I removed the theme's config file, everything worked as expected

Thank you 👍

**Comment by lukeorth** [comment]
Perfect! I'm glad to hear it's working now. 🙂
