### ISSUE TITLE
extremely high cpu usage on demo site

### ISSUE THREAD

**Issue by sybenx** [lukeorth/poison#134]
https://poison.lukeorth.com/posts/introducing-poison/

![image](https://github.com/lukeorth/poison/assets/2048087/d1c680e9-f7fd-48b4-a8fd-f56ec4be71b2)

**Comment by lukeorth** [comment]
Wow, you're right... If I leave it open even for a bit, my fan starts to kick up.

I think this has to do with how I've included Mermaid JS, but I need to investigate more.  Thanks for pointing this out. :+1:

**Comment by lukeorth** [comment]
I was wrong... it seems to be 100% related to Disqus.  I'll probably just have to remove it from the demo site.

**Comment by lukeorth** [comment]
Removing Disqus from demo site and closing this issue.
