### ISSUE TITLE
code content overflowing on mobile

### ISSUE THREAD

**Issue by rawwerks** [lukeorth/poison#139]
today i noticed that the `code` blocks overflow off to the right on mobile:

<img width="404" alt="image" src="https://github.com/lukeorth/poison/assets/19483938/4b953a66-1079-4510-a76f-c138b5295a6f">

i was able to fix it with this overwrite (in `custom.css`)

```
.content pre code {
  max-width: 100%;
  overflow-x: auto;
  word-break: normal;
  word-wrap: normal;
  white-space: pre-wrap;
}
```

since some of these CSS overwrites might not be desired, i will let @lukeorth decide how to fix this. it's a little confusing to me, since this is set "in stages" by hyde.css, poole.css, and poison.css.

**Comment by lukeorth** [comment]
Hi, @rawwerks -- thanks for reporting this.  

It's interesting that you prefer the code to be wrapped.  I actually prefer for it to overflow horizontally with the option to scroll, but can understand how people might have differing opinions. :wink:  

I think for the time being I'll leave it as is.  However, I do think this can be useful to others that want to customize their CSS to a different taste. :+1:
