### ISSUE TITLE
Menu names have to match content folder name

### ISSUE THREAD

**Issue by HardwoodHomelab** [lukeorth/poison#14]
There is an issue with the way menu items work. I can't use 2 word menu items with spaces. Because the menu name and URL have to match in the config.toml file, this basically makes 2 word menu items impossible because the link that is created with a space does not match the URL.

Plus, the home page only shows content from the posts directory. This means that I cannot rename the posts menu and have my posts show on the homepage. It would be convenient if there was a way to have the menu items allow sub-directories. For example "{Name = "Menu Item 1", URL = "/posts/menu_1", Pre = "Recent", HasChildren = true, Limit = 5}, {Name = "Menu Item 2", URL = "/posts/menu_2", Pre = "Recent", HasChildren = true, Limit = 5},"  This would allow posts that you may not want in the home page to use a separate directory and menu item in the contents directory. It would allow much more flexibility.

Plus menu items with capitol letters that are not the first letter in the name will not match either.

**Comment by lukeorth** [comment]
Hi @HardwoodHomelab, thanks for the report!

Yes I agree --- the inability to use multiword menu items *and* the inability to use capitol letters are definitely issues.  I will work on getting those fixed.

For your request to add support for sub-directories, are you asking that the sidebar be capable of looking something like this (assuming the configs you provided above)?  Or did you have something else in mind?

```
Posts (dir)
  |
  Post 1
  Post 2
  Menu 1 (dir)
    |
    Sub-post 1
    Sub-post 2
  Menu 2 (dir)
    |
    Sub-post 1
    Sub-post 2
```

**Comment by HardwoodHomelab** [comment]
Not that the sidebar menu would reflect the directory structure. More so, that the menu system could be somewhat independent of the directory structure of the /contents/ directory. The side menu would look consistent with your example site.

```
Menu 1
    recent
    sub-post 1
    sub-post 2
Menu 2
    recent
    sub-post 1
    sub-post 2
Menu 3
Word Of The Day
   sub-post 1
   sub-post 2
```
But the directory structure within the contents directory would more or less be consistent with your example.

```
content/
     |
   posts/
          |
      Menu_1/
              |
            Series1-Post1.md
            Series1-Post2.md
       Menu_2/
               |
             Series2-Post1.md
             Series2-Post2.md
      |
   Menu_3/
            |
         Single-Page.md
      |
   wotd/
             |
          Series3-Post1.md
          Series3-Post2.md
```
This would allow any posts placed under the /posts/ directory to auto fill on the home page. Anything outside the posts directory could be have it's own menu item but not necessarily show up on the homepage. Could somewhat allow modifying the url. Would allow in the example above, the "word of the day" posts to be http://domain.com/wotd/Series3-Post1 instead of a much longer http://domain.com/word-of-the-day/Series3-Post1.

**Comment by lukeorth** [comment]
Ah I see, thanks for the clarification.  I agree that your proposal would provide more flexibility.  Unfortunately, I don't know that it's something I want to add to the theme...  I'm trying to keep things relatively simple, and I think implementing this would require additional keys in the `menu` site config.

That said, I think you could achieve similar results by restructuring things a bit.  For example, by moving the `Menu_1` and `Menu_2` directories outside of posts, you could make them root sections under `content`:

```
content/
     |
   Menu_1/
           |
         Series1-Post1.md
         Series1-Post2.md
   Menu_2/
           |
         Series2-Post1.md
         Series2-Post2.md
   Menu_3/
           |
        Single-Page.md
   wotd/
           |
        Series3-Post1.md
        Series3-Post2.md
```
Then you can copy `poison/layouts/index.html` into your own `layouts`, which will override just that portion of the theme.  Then all you'd have to do is modify it to range over the `Menu_1` and `Menu_2` sections instead of `posts`.

**Comment by HardwoodHomelab** [comment]
Thank you. This is a much easier solution. I have zero experience with HTML code or coding in general, so I had no clue how to achieve this. So only issue is capitol letters and multi word menu items.

**Comment by lukeorth** [comment]
Of course --- I'm glad it helped!

I'm about to merge a fix for the capitalization and multi-word issues, so hopefully that resolves things for you.
