### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by ats20de** [lukeorth/poison#149]
Hi Luke,

is it possible to configure Poison for full entries on the start page (so that the reader has not to click "read more")?

However: thanks for your work on the Poison theme! –

Regards,
Hanjo.

**Comment by lukeorth** [comment]
Hi @ats20de - I'm glad you're enjoying the theme!

I just merged an update that will enable this request.  To have _all_ articles/posts fully displayed on the home page (i.e. without content summaries or the "Read More" button), you will need to add the `noSummary = true` param to your project's `config.toml` file.  The last line of this code block shows an example:

```
baseURL = "https://myurl.com"
theme = "poison"
paginate = 10

[params]
    brand = "My Brand"
    noSummary = true
```

Alternatively, if you only want this enabled for specific articles/posts, you can set the `noSummary = true` value in the applicable post's front matter.  For example:

```
---
title: "For My Mom"
date: 2023-10-26T11:52:03-06:00
draft: false
noSummary: true
---

Hi mom.
```

Hopefully this meets your requirements.  Let me know if you need anything else!

**Comment by ats20de** [comment]
That’s great – thanks a lot, Luke!

Regards,
Hanjo.
