### ISSUE TITLE
RSS link is broken

### ISSUE THREAD

**Issue by n0rdy** [lukeorth/poison#157]
Hello there, Luke!

I finally deployed my blog using the Poison theme (have I already said that it's an awesome one?) and it was quite a smooth process - thanks for that!

There are some tiny things that I've noticed and decided to let you know, as it might be smth worth fixing if you agree.

One important thing that I've experienced is a broken RSS link. Let me elaborate on this:
- here is [the link to my blog](https://n0rdy.foo/)
- RSS is enabled there via the following properties
```
    rss_icon = true
    rss_section = "posts"
```
- if you click on the RSS link on my website, it will lead to this link: https://n0rdy.foo//posts/index.xml - please, notice that it has 2 slashes `//` before the `posts` subpath. If I remove one of them, the link works
- the strange part is that I can see that your blog relies on 2 slashes `//` for RSS too, and it works well: here is your link - https://lukeorth.com//posts/index.xml
- I use the latest Poison version, here is [the link to my repo with the blog](https://github.com/n0rdy/n0rdy-blog) if that helps

Could it be that your blog uses an older version of Poison, and in between that one and the latest one some bug was introduced regarding RSS?

Thanks!

Have fun,
n0rdy

**Comment by sudomateo** [comment]
I ran into this issue too. It's not an issue with the version of the theme, but rather the web server that's serving the built website. Some web servers are okay with serving those double leading slashes and others aren't. I tested it locally a few months ago using different web servers but I didn't document my results.

#163 is already open to fix this. It's a small code fix too. Perhaps it'll get merged and released soon.
