### ISSUE TITLE
Display author in post info

### ISSUE THREAD

**Issue by ctmbl** [lukeorth/poison#170]
I've searched [poison's issues](https://github.com/lukeorth/poison/issues) for similar feature proposal because I found it weird that nobody suggested such thing before but didn't find any, if I missed it, sorry for the duplicate issue :sweat_smile: 

## Proposal
- I'd like to had post author to the post info (if present in metadata) just before date in `layouts/partials/post/info.html`
- The author could be an hyperlink, or not, given if `author` is a taxonomy or not to the website
- I could add appropriated CSS if someone has a suggestion about how it could look :slightly_smiling_face: 

## Demo
it would look like this:
![Screenshot_20240318_123620](https://github.com/lukeorth/poison/assets/79016298/fcc8a6a2-bf49-4c63-88f7-86a2f71245a1)

(currently down but should be up soon at https://iscsc.fr/posts/publish-your-own-post)

**Comment by lukeorth** [comment]
Hi, @ctmbl -- thanks for the suggestion!  I think this would be a great addition to the theme.  Regarding how it should look, I think what you have in the screenshot looks good.  It looks "on brand" with the rest of the theme.

If you want to put together a PR, I'd be happy to review. :slightly_smiling_face:

**Comment by ctmbl** [comment]
Hi @lukeorth tks for your positive answer!
I have a PR almost ready on my own fork, I'll open one here soon 😉
