### ISSUE TITLE
Use of .Site.DisqusShortname is deprecated

### ISSUE THREAD

**Issue by danielcorin** [lukeorth/poison#189]
It seems the `.Site.DisqusShortname` used in the theme is being deprecated. The convention is now to use `.Site.Config.Services.Disqus.Shortname`.

```sh
Start building sites … 
hugo v0.126.1+extended darwin/arm64 BuildDate=unknown VendorInfo=nixpkgs

WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
```

This variable is currently used [here](https://github.com/lukeorth/poison/blob/4b36ef57e6834471d946d634f9677971b5acc43e/layouts/_default/single.html#L9) and [here](https://github.com/lukeorth/poison/blob/4b36ef57e6834471d946d634f9677971b5acc43e/layouts/partials/post/comments.html#L17).

Migrating to the new convention should be straightforward but it will depend if there's a need to make the new approach backwards compatible. I'd be happy to submit a PR if someone can advise on the preferred approach going forward.

**Comment by James-Randall-14** [comment]
Also running into this issue

**Comment by menteb** [comment]
I created a [pull request](https://github.com/lukeorth/poison/pull/194) (#194) for this now.

**Comment by James-Randall-14** [comment]
trying it out right now, works great

**Comment by lukeorth** [comment]
Thank you for reporting this, @danielcorin!  I have merged @menteb's PR to fix this issue.
