### ISSUE TITLE
Add different social icons

### ISSUE THREAD

**Issue by dldsantos** [lukeorth/poison#2]
So, I saw social icons in Poison are actually textual representations of SVG files, instead of icons as other themes use them. Thus, I'd like help/ directions on what to do to add additional social icons as SVG. I'm thinking about Mastodon, [Micro.blog](https://micro.blog), [Literal.club](https://literal.club/), besides an e-mail and RSS feed icons.

Can you point me out on how to do it? 

Thanks!

**Comment by dldsantos** [comment]
I ended up figuring out my way with a little help from Inkscape and simple SVG files... I have shared my complementary social icons [here in this paste bin](https://home.omg.lol/address/daniel/pastebin/additional-svg-social-icons-for-hugos-poison-theme), if anyone is interested.

**Comment by lukeorth** [comment]
Hi @dldsantos, thanks for sharing!  I'm sure others will find those useful.

My method is usually to just search for an icon on iconify (https://iconify.design/), choose the SVG option, and copy/paste the code from there.  It's a bit more tedious than using a library like Font Awesome, but keeps things simple and reduces dependencies.

I'm glad you're enjoying the theme. :slightly_smiling_face:

**Comment by dldsantos** [comment]
Thanks for your answer, @lukeorth. I didn't know Iconify, and now that I do, I acknowledge it's a very valuable resource that I've bookmarked right away. It's much easier to look for data there, for sure.
