### ISSUE TITLE
Unnecessary Scroll Bar in Sidebar

### ISSUE THREAD

**Issue by maheenwaris** [lukeorth/poison#200]
There’s an unexpected scroll bar at the bottom of the sidebar in the **Poison** theme, as shown in the attached screenshot. The content doesn't require scrolling, so the bar shouldn't appear.
**Steps to Reproduce**:
1. Open a site using the Poison theme.
2. Notice the scroll bar in the sidebar.

**Expected Behavior**:  
The sidebar should only show a scroll bar if the content exceeds the container's height.

**Screenshot**: 
![image](https://github.com/user-attachments/assets/2baa3ca2-731b-4205-b4b9-90d9290a97bd)

Would you be interested if I fix this? Thanks for your work on the theme!

**Comment by pspspsecurity** [comment]
It seems to me like the site itself has grown to be 20% too large. You might also notice that the navigation pane on the right is being hidden by default due to width constraint. If you zoom to 80% the theme appears as expected.
