### ISSUE TITLE
Menu URLs

### ISSUE THREAD

**Issue by RonBulaon** [lukeorth/poison#27]
menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Series", URL = "/series/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 10},
    ]

Hi there! I'm new to this Hugo and Posison template. I have an issue, I have this (above) configured on ```config.toml``` but only **About** and **Post** are showing up in the side menu. The **Series** is **not** showing up or any other menu item I add.

Thanks in advance!

Ron

**Comment by lukeorth** [comment]
Hi @RonBulaon - thank you for using the theme!

So the sidebar menu will only show items that:

1. Are listed in your config (which it looks like you do) and
2. Actually exist in your content directory

Take a look at issue #6 and let me know if you're still having issues.  I think it should address your issue.  

Also keep in mind that if your content's front matter has `draft: true` then Hugo pretends it doesn't exist, so you'll want to make sure you have it set to `draft: false`.

**Comment by RonBulaon** [comment]
Thank you!
