### ISSUE TITLE
Tabs not responding

### ISSUE THREAD

**Issue by sbruyere** [lukeorth/poison#31]
Hello, 
I've setup your great Poison theme for gohugo, but it seems like the "Tabs" feature is broken and is not responding to click.

You can experience it directly from your demo: https://poison-theme.netlify.app/posts/introducing-poison/ trying to change tab doesn't work.

Thanks, 
Sylvain

**Comment by lukeorth** [comment]
Thanks for reporting this, @sbruyere!  That is definitely an issue.  Adding a fix for it now.
