### ISSUE TITLE
Tables in darkmode are unreadable

### ISSUE THREAD

**Issue by sbruyere** [lukeorth/poison#32]
Hello !

I've an issue with color alternation in the table with dark mode as the contrast between the alternate rows is significantly higher than that of the odd rows. This issue makes the table nearly illegible in dark mode. To illustrate, consider the following example:

![image](https://user-images.githubusercontent.com/12117266/219074115-94792a46-05cf-41d2-96c9-d8c49d100aad.png)

**Comment by lukeorth** [comment]
Thanks, @sbruyere -- another good catch!  I will work on a fix for this.
