### ISSUE TITLE
Post dates are not correctly rendered in lists

### ISSUE THREAD

**Issue by traveltissues** [lukeorth/poison#35]
Post dates are always displayed as `:date_long`

example front matter:
```
---
date: 2010-05-14
---

```
is being displayed in the post lists as
![Screenshot from 2023-03-01 15-07-14](https://user-images.githubusercontent.com/37911360/222179618-218f4bc7-679f-45a5-80fd-676119caf49f.png)

**Comment by lukeorth** [comment]
Hi @traveltissues - thank you for contributing!  I'm glad you're enjoying the theme.

If possible, could you please elaborate some more on where this issue is cropping up?  I want to be able to replicate the issue on my end.  If you could, please also include a screenshot of the entire page (including the sidebar).  That will help me a bit more.

Thanks again!

**Comment by traveltissues** [comment]
> Hi @traveltissues - thank you for contributing! I'm glad you're enjoying the theme.
> 
> If possible, could you please elaborate some more on where this issue is cropping up? I want to be able to replicate the issue on my end. If you could, please also include a screenshot of the entire page (including the sidebar). That will help me a bit more.
> 
> Thanks again!

Hi, thanks for having a look. I will try to recreate this on my end so I can provide some more details.

**Comment by lukeorth** [comment]
No worries!  I've seen that happen before with  `hugo server`.  Glad to hear everything is resolved.

**Comment by losthearts** [comment]
Hi. I am currently facing this issue.

https://xn--f9jvei1272bn4g.yokohama/posts/

```md
---
title: "I am not Japanese."
date: 2024-03-24
draft: false
tags: ["Personal"]
---

I do not speak Japanese, nor can I read or comprehend it.

I am just an individual with a computer.

<!--more-->
---

- "失われた心" stands for "lost hearts".
- "私たちはみんな迷っている、それでいいんだ。" stands for "We're all lost, and that's okay".

---

Japanese is a language spoken by over 120 million speakers.
It has a certain charm to it just like every other language belonging to a culturally rich country.

I have used [DeepL](https://www.deepl.com/translator) and [Go*gle Translate](https://translate.google.com/) to help make this site.
```

**Comment by losthearts** [comment]
I can confirm that it is a netlify problem and I do apologise for the previous comment.
