### ISSUE TITLE
Description only readable in dark mode

### ISSUE THREAD

**Issue by tgamblin** [lukeorth/poison#40]
<img width="344" alt="Screenshot 2023-03-04 at 9 39 52 PM" src="https://user-images.githubusercontent.com/299842/222943618-ce0b07eb-9c95-4b09-bf30-2d229d63cf91.png">
<img width="342" alt="Screenshot 2023-03-04 at 9 39 48 PM" src="https://user-images.githubusercontent.com/299842/222943619-51208e6e-1991-42ae-9104-a6cafaeb5f28.png">

See examples here -- looks like the description only shows up in dark mode.

**Comment by lukeorth** [comment]
Thank you for reporting this, @tgamblin.  I'm working on the fix now.

**Comment by lukeorth** [comment]
This is now fixed.  Sorry for any inconvenience! :)

**Comment by tgamblin** [comment]
Works great!  Thanks so much!
