### ISSUE TITLE
Add taxonomies as menu items

### ISSUE THREAD

**Issue by nitishingde** [lukeorth/poison#44]
```toml
menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Series", URL = "/series/", HasChildren = false}, #doesn't work
        {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 5},
]
```

It would be nice if you could support adding taxonomies like "series" and "tags" as menu items.

**Comment by lukeorth** [comment]
Hi @nitishingde - thanks for the recommendation.  I agree this would be a nice feature.  Does the picture below reflect what you had envisioned?

![image](https://user-images.githubusercontent.com/35306887/223531344-d85209b5-2c31-451e-9235-2042f04400e7.png)

**Comment by nitishingde** [comment]
Yes.
