### ISSUE TITLE
Where to put index page to be displayed at page load

### ISSUE THREAD

**Issue by snow-kluster** [lukeorth/poison#45]
I want to a index page to load when at the root of the site like in the [example](https://poison-theme.netlify.app/) and be able to return to this index page when clicking the brand name.

How do you accomplish this??
@lukeorth

**Comment by lukeorth** [comment]
Hi @snow-kluster - thanks for the question.  Clicking on the brand name (or title of the site) will take you to whatever path is set in `baseURL` in your config file.  So if the index of your site exists at _https://snowkluster.com_, then that's the value that should be set for `baseURL` in your config file.  Does that make sense?

Here's the link to my `config.toml` file I'm using for the _Poison_ demo site if that helps.  

Let me know if you need anything else or if I can close this as complete. :)

**Comment by snow-kluster** [comment]
> Hi @snow-kluster - thanks for the question. Clicking on the brand name (i.e. the title of the site) will take you to whatever path is set as the `baseURL` in your config file. So if the index of your site exists at _https://snowkluster.com_, then that's the value that should be set for `baseURL` in your config file. Does that make sense?
> 
> Here's the link to my `config.toml` file I'm using for the _Poison_ demo site if that helps.
> 
> Let me know if you need anything else or if I can close this as complete. :)

understood, thanks for the help
