### ISSUE TITLE
Posts do not use real-estate effectively

### ISSUE THREAD

**Issue by traveltissues** [lukeorth/poison#51]
There's quite a lot of whitespace between the post column bound and the TOC in 1920px. I'd like to set dimensions relative to the window in poison.css (since I think this change will be useful to most poison users too) - currently things are being set relative to font-size
![screenshot 2](https://user-images.githubusercontent.com/37911360/224002269-5d1b3be6-e4e6-483e-a1a6-4f02f0e8daa1.jpg)

**Comment by KarlAustin** [comment]
If you see: https://github.com/lukeorth/poison/issues/52#issuecomment-1462409015 it's down to the TOC having a 50% left on it.

**Comment by traveltissues** [comment]
I'm happy for this to be closed
