### ISSUE TITLE
Decrease width for activating TOC

### ISSUE THREAD

**Issue by traveltissues** [lukeorth/poison#52]
Currently I think there's enough room on the right-hand side to allow TOC to be active at a smaller window size (see below)

![screenshot 3](https://user-images.githubusercontent.com/37911360/224005901-73e53900-bea9-4b87-b1c7-e293d8a95c38.jpg)

**Comment by KarlAustin** [comment]
I've just tested re-arranging some of the HTML and semantics to allow flexbox:

https://github.com/lukeorth/poison/compare/master...KDAWS-com:poison-toc-semantics:master

![image](https://user-images.githubusercontent.com/5338970/224097303-41d1e081-6a01-4406-affd-7edfc51922f9.png)

That's how it looks on my 4k screen by default now - no big gap (there's more space off to the right)

**Comment by traveltissues** [comment]
I'm happy for this to be closed
