### ISSUE TITLE
Any other side bar item other then projects.

### ISSUE THREAD

**Issue by sai-sy** [lukeorth/poison#6]
I do the code you put as an example for projects. It works like a charm. I change the folder name and the config file and it doesn't work anymore. I can't custom name side bar sections? Why does it only give me a section when it is called project? Love the theme otherwise thank you!

**Comment by lukeorth** [comment]
Hi @sai-sy, I'm glad you're enjoying the theme!

The sidebar menu will only show items that:
1. Are listed in your config *and*
2. Actually exist in your `content` directory

I added a *Test* sidebar item in the following screenshot to demonstrate.

![image](https://user-images.githubusercontent.com/35306887/212546898-82989639-97ef-4e5e-bb9b-22f74db8a925.png)

The *Test* item is only shown because I've included it in my config:

```toml
menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Test", URL = "/test/", HasChildren = false},
    ]
```

*And* I have a `test` directory inside of my `content` directory which has a markdown file.  So I have the following structure:

`project_home/content/test/test.md`

Hopefully that helps!

**Comment by sai-sy** [comment]
I thought so but I have 4 directories
![image](https://user-images.githubusercontent.com/74868837/212587649-a3bdeab1-f8ba-4c74-9d50-8fab0ec66752.png)
with a config file like this
```toml
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Projects", URL = "/projects/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Project", URL = "/project/", Pre = "Recent", HasChildren = true, Limit = 5},
	    {Name = "Test", URL = "/test/", HasChildren = true},
]
```
And yet my output looks like this
![image](https://user-images.githubusercontent.com/74868837/212587516-b42db3c8-771e-4936-bfba-1fcc8b9b03f7.png)

I'm super confused on why /project/ displays as Projects and why test doesn't show up at all. Thanks!

**Comment by maccident** [comment]
> I'm super confused on why `/project/` displays as Projects and why `/test/` doesn't show up at all. Thanks!
I believe it's there, but the sidebar does not scroll down, so it is off the screen.
In your browser, go to View then select Zoom Out a few times…  I bet you'll see it.
At a minimum, you should see the copyright notice.

**Comment by sai-sy** [comment]
Doesn't explain why `/project/` is displayed as Projects when it's explicitly told not to. Super weird. I changed my test to copy your original config and directory example with the test and tried zooming out. Nothing shows up. In the screenshot the copyright is just cropped out. Maybe I configured hugo somewhere else wrong

**Comment by sai-sy** [comment]
To confirm, all my config work should be done in `./config.toml` not ./themes/poison/config.toml`. I assume hugo only needs the `theme = 'poson'` to understand where to get the ./themes/poison/layouts/partials/sidebar/menu.html` information

**Comment by maccident** [comment]
@sai-sy 
> To confirm, all my config work should be done in `./config.toml` not `./themes/poison/config.toml`. I assume hugo only needs the `theme = 'poson'` to understand where to get the ./themes/poison/layouts/partials/sidebar/menu.html` information

Here is my menu section:
```
  menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Authors", URL = "/authors/", HasChildren = false},
    {Name = "Categories", URL = "/categories/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    {Name = "Series", URL = "/series/", HasChildren = false, Limit = 5},
    {Name = "Tags", URL = "/tags/", HasChildren = false},
  ]
```
You need to make each directory and place a file (empty is fine) in each menu directory.
For example, I have an empty file in content/about/markdown.md
Same for each other directory.

**Comment by sai-sy** [comment]
That's exactly how I have it. Maybe I've configured hugo or go wrong because the behaviour I'm getting seems random and unrepeatable. Thank you for the support and great work on a beautiful theme.
