### ISSUE TITLE
Code Snippets Copy Button

### ISSUE THREAD

**Issue by Diogo-Almeida3** [lukeorth/poison#63]
Greetings,
I have been attempting to incorporate a copy button into code snippets, however, I wasn't successful in doing so. I would really appreciate any help in implementing this feature. 
Thank you.

**Comment by ARBoyGo** [comment]
Mm, That'll be an amazing feature.

**Comment by lukeorth** [comment]
Thanks to @JMicheli, this feature has been added. :tada:
