### ISSUE TITLE
Images not displaying in posts on main page

### ISSUE THREAD

**Issue by kmkrebs** [lukeorth/poison#67]
I'm think this is more my ignorance than an issue, but when I have images in a post they don't appear on the main page.  To see them you need to click on the post itself. 

I have previously used the [Strange Case](https://github.com/ExchangeRate-API/strange-case) theme and this worked as I expected it to.

I tried consulting the Hugo documentation, but it was a bit over my head.  It's certainly not a show-stopper, but if anyone knows how to get this working, I would appreciate it.

thanks,

**Comment by lukeorth** [comment]
Hi @kmkrebs, thank you for the question!  Hopefully this helps others that might experience similar issues.

Hugo has [several different ways of rendering content summaries](https://gohugo.io/content-management/summaries/).  It sounds like you're using automatic summary splitting, which takes the first 70 words of content by default and displays that.  From my experience, this doesn't typically capture images or other "non-word" HTML elements.  

My workaround for this is to use manual summary splitting with the `<!--more-->` divider.  Any content above this divider will be included in the summary, including images.

Here's an example:
![image](https://user-images.githubusercontent.com/35306887/234248801-2f356c39-5009-448a-8563-4114e809d201.png)
![image](https://user-images.githubusercontent.com/35306887/234248897-d7988f64-312b-46f7-8611-5c435f1d5f5e.png)

**Comment by kmkrebs** [comment]
Thank you! It's such a simple and elegant solution.  I hope this helps others too.
