### ISSUE TITLE
mailto social link icon doesn't have a stroke color by default

### ISSUE THREAD

**Issue by delroth** [lukeorth/poison#79]
`stroke="{{ .Site.Params.sidebar_bg_color }}"`

If sidebar_bg_color is not explicitly set in the site's params, the mailto envelope icon is just a white rectangle. This should likely default to the same #202020 as used in the CSS. Alternatively, this could be hardcoded like every other social icon's stroke color.

**Comment by lukeorth** [comment]
Good catch, @delroth.  Thank you!
