### ISSUE TITLE
Add sidebar social icon for `telegram` and `phone number`

### ISSUE THREAD

**Issue by hntan** [lukeorth/poison#82]

**Comment by lukeorth** [comment]
![image](https://github.com/lukeorth/poison/assets/35306887/f7013423-7ffc-46a9-b451-c65e52de3d4d)

I added the Telegram icon in the sidebar.  You can activate it by adding `telegram_url = "https://your_telegram_link"` to your `config.toml` file.

I haven't used Telegram before, so let me know if this isn't how it works. :slightly_smiling_face: 

Thanks for the suggestion!
